kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mongodb
  labels:
    app: mongodb
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

