apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-sfs
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-hd-service
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.0.17
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
  
        volumeMounts:
        - name: pvc-sfs
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: pvc-sfs
     
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
