kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-mongodb
  labels:
    type: local
    app: mongodb
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/mongodb/data
