apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: deploy-readereditor
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]