apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-edit-deployment
  namespace: test-namespace
subjects:
- kind: User
  name: alex
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deploy-readereditor
  apiGroup: rbac.authorization.k8s.io