apiVersion: apps/v1
kind: Deployment
metadata:
  name: sns-api-deployment
  labels:
    app: snsrestapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snsrestapi
  template:
    metadata:
      labels:
        app: snsrestapi
    spec:
      containers:
      - name: sns-api-container
        image: tzerok/snsrestapi:v11
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: MONGO_DB_URL
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: sns-api-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: snsrestapi

